---
- name: Get service facts
  service_facts:

- name: Ensure {{ group }} group exists
  group:
    name: "{{ group }}"
    state: present
  tags:
    - kafka_exporter_install

- name: Ensure {{ user }} user exists
  user:
    name: "{{ user }}"
    shell: /sbin/nologin
    group: "{{ user }}"
  tags:
    - kafka_exporter_install

- name: Ensure {{ user }} user exists
  user:
    name: "{{ user }}"
    shell: /sbin/nologin
    group: "{{ user }}"
  tags:
    - kafka_exporter_install

- name: Check if tar file exists
  stat:
    path: "{{ file_path }}"
  register: file_stat_result
  tags:
    - kafka_exporter_install

- name: Download tar.gz file
  get_url:
    url: "{{ download_url }}"
    dest: "{{ base_dir_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0640
  when: not file_stat_result.stat.exists
  tags:
    - kafka_exporter_install

- name: Check if directory exists
  stat:
    path: "{{ folder_path }}"
  register: directory_stat_result
  tags:
    - kafka_exporter_install

- name: Extract tar.gz file
  unarchive:
    src: "{{ file_path }}"
    dest: "{{ base_dir_path }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    remote_src: true
  tags:
    - kafka_exporter_install

- name: Create a symlink of kafka_exporter binary
  file:
    src: "{{ folder_path }}/kafka_exporter"
    dest: "/usr/local/bin/kafka_exporter"
    owner: "{{ user }}"
    group: "{{ group }}"
    state: link
  tags:
    - kafka_exporter_install

- name: Transfer template files to the remote host
  template:
    src: kafka-exporter.service.j2
    dest: "/etc/systemd/system/{{ systemd_service_name }}.service"
    owner: root
    group: root
    mode: 0640
  tags:
    - kafka_exporter_configure
  notify:
    - start and enable kafka-exporter
