---
- name: force systemd to reread configs
  systemd:
    daemon_reload: true

- name: start and enable kafka-exporter
  systemd:
    name: "{{ systemd_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
